name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]
  
  workflow_dispatch:
  
jobs:
  bluid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, wolrd!
        
      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
